services:
  # Backend API service (not publicly accessible)
  - type: web
    name: gpt-researcher-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LOGGING_LEVEL
        value: INFO
    disk:
      name: gpt-researcher-data
      mountPath: /usr/src/app/outputs
      sizeGB: 10
    autoDeploy: false
    # Make this service private (not publicly accessible)
    private: true

  # Frontend NextJS service (publicly accessible)
  - type: web
    name: gpt-researcher-frontend
    env: docker
    dockerfilePath: ./frontend/nextjs/Dockerfile.dev
    dockerContext: ./frontend/nextjs
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_GPTR_API_URL
        fromService:
          name: gpt-researcher-api
          type: web
          property: host
        # Prepend with https:// and append with port
        value: https://$$HOST:8000
      - key: NEXT_PUBLIC_GA_MEASUREMENT_ID
        sync: false
      - key: CHOKIDAR_USEPOLLING
        value: "true"
      - key: NODE_ENV
        value: production
    autoDeploy: false

# Define a disk for persistent storage
disks:
  - name: gpt-researcher-data
    mountPath: /usr/src/app/outputs
    sizeGB: 10
