# Render Blueprint specification
services:
  # Backend API service (not publicly accessible)
  - type: web
    name: gpt-researcher-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    branch: master
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LOGGING_LEVEL
        value: INFO
    disk:
      name: gpt-researcher-disk
      mountPath: /usr/src/app/outputs
      sizeGB: 10
    autoDeploy: false

  # Frontend NextJS service (publicly accessible)
  - type: web
    name: gpt-researcher-frontend
    runtime: docker
    dockerfilePath: ./frontend/nextjs/Dockerfile.dev
    dockerContext: ./frontend/nextjs
    plan: standard
    branch: master
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_GPTR_API_URL
        value: http://gpt-researcher-api:8000
      - key: NEXT_PUBLIC_GA_MEASUREMENT_ID
        value: ""
      - key: DISCORD_BOT_TOKEN
        value: ""
      - key: DISCORD_CLIENT_ID
        value: ""
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 3000
      # Memory optimization settings
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      # Disable file watching to reduce memory usage
      - key: CHOKIDAR_USEPOLLING
        value: "false"
      # Disable telemetry
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      # Garbage collection settings
      - key: NODE_GC_INTERVAL
        value: "5000"
    autoDeploy: false
